#!/bin/bash

# Interactive setup script for Gerbil AI Suite
# Prompts for environment variables and tests connectivity
# Runs before devcontainer starts

set -e

ENV_FILE=".env"

echo "🚀 Gerbil AI Suite - Environment Setup"
echo ""

# Check if .env already exists and is valid
if [ -f "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    echo "✅ Environment file (.env) already exists."
    echo "If you need to reconfigure, delete .env and rebuild the container."
    echo ""
    exit 0
fi

echo "📝 Please provide the following information:"
echo ""

# Prompt for Grafana URL
while true; do
    read -p "🌐 Grafana URL (e.g., https://your-grafana.com): " GRAFANA_URL
    if [ -z "$GRAFANA_URL" ]; then
        echo "❌ URL cannot be empty. Please try again."
        echo ""
        continue
    fi
    if [[ ! "$GRAFANA_URL" =~ ^https?:// ]]; then
        echo "❌ Please enter a valid HTTP or HTTPS URL."
        echo ""
        continue
    fi
    break
done

# Prompt for Service Account Token
while true; do
    read -p "🔑 Grafana Service Account Token: " GRAFANA_SERVICE_ACCOUNT_TOKEN
    if [ -z "$GRAFANA_SERVICE_ACCOUNT_TOKEN" ]; then
        echo "❌ Token cannot be empty. Please try again."
        echo ""
        continue
    fi
    if [ ${#GRAFANA_SERVICE_ACCOUNT_TOKEN} -lt 10 ]; then
        echo "❌ Token seems too short. Please check and try again."
        echo ""
        continue
    fi
    break
done

# Test Grafana connectivity
echo ""
echo "🔍 Testing Grafana connection..."

API_URL="${GRAFANA_URL%/}/api/org"

if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -s -o /tmp/grafana_response.json -w "%{http_code}" \
        -H "Authorization: Bearer $GRAFANA_SERVICE_ACCOUNT_TOKEN" \
        -H "Content-Type: application/json" \
        "$API_URL" 2>/dev/null || echo "000")

    if [ "$HTTP_CODE" -eq 200 ]; then
        ORG_NAME=$(grep -o '"name":"[^"]*"' /tmp/grafana_response.json 2>/dev/null | cut -d'"' -f4 || echo "Unknown")
        echo "✅ Successfully connected to Grafana organization: $ORG_NAME"
        rm -f /tmp/grafana_response.json
    else
        echo "❌ Connection test failed (HTTP $HTTP_CODE)"
        rm -f /tmp/grafana_response.json
        read -p "⚠️  Continue anyway? (y/N): " CONTINUE
        if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
            echo "Setup cancelled."
            exit 1
        fi
    fi
else
    echo "⚠️  curl not found, skipping connection test"
fi

# Create .env file
cat > "$ENV_FILE" << EOF
# Grafana Configuration
GRAFANA_URL=$GRAFANA_URL
GRAFANA_SERVICE_ACCOUNT_TOKEN=$GRAFANA_SERVICE_ACCOUNT_TOKEN

# Generated by setup script on $(date -Iseconds 2>/dev/null || date)
EOF

echo ""
echo "✅ Environment file created successfully: $ENV_FILE"
echo "🎉 Setup complete! The devcontainer will now start."
echo ""
