#!/bin/bash

# Interactive setup script for Gerbil AI Suite
# Prompts for environment variables and tests connectivity
# Runs before devcontainer starts

set -e

ENV_FILE=".env"

echo "🚀 Gerbil AI Suite - Environment Setup"
echo ""

# Check if .env already exists and is valid
if [ -f "$ENV_FILE" ] && [ -s "$ENV_FILE" ]; then
    echo "✅ Environment file (.env) already exists."
    echo "If you need to reconfigure, delete .env and rebuild the container."
    echo ""
    exit 0
fi

echo "📝 Please provide the following information:"
echo ""

# Prompt for Grafana URL
while true; do
    read -p "🌐 Grafana URL (e.g., https://your-grafana.com): " GRAFANA_URL
    if [ -z "$GRAFANA_URL" ]; then
        echo "❌ URL cannot be empty. Please try again."
        echo ""
        continue
    fi
    if [[ ! "$GRAFANA_URL" =~ ^https?:// ]]; then
        echo "❌ Please enter a valid HTTP or HTTPS URL."
        echo ""
        continue
    fi
    break
done

# Prompt for Service Account Token
while true; do
    read -p "🔑 Grafana Service Account Token: " GRAFANA_SERVICE_ACCOUNT_TOKEN
    if [ -z "$GRAFANA_SERVICE_ACCOUNT_TOKEN" ]; then
        echo "❌ Token cannot be empty. Please try again."
        echo ""
        continue
    fi
    if [ ${#GRAFANA_SERVICE_ACCOUNT_TOKEN} -lt 10 ]; then
        echo "❌ Token seems too short. Please check and try again."
        echo ""
        continue
    fi
    break
done

# Prompt for Bugsnag Auth Token
echo ""
echo "📋 To get your Bugsnag Auth Token:"
echo "   1. Go to https://app.bugsnag.com"
echo "   2. Navigate to Settings → My Account → Auth Tokens"
echo "   3. Or visit: https://app.bugsnag.com/settings/<your-org>/my-account/auth-tokens"
echo "   4. Click 'Generate new token' and copy it"
echo ""
while true; do
    read -p "🐛 Bugsnag Auth Token: " BUGSNAG_AUTH_TOKEN
    if [ -z "$BUGSNAG_AUTH_TOKEN" ]; then
        echo "❌ Auth Token cannot be empty. Please try again."
        echo ""
        continue
    fi
    if [ ${#BUGSNAG_AUTH_TOKEN} -lt 10 ]; then
        echo "❌ Auth Token seems too short. Please check and try again."
        echo ""
        continue
    fi
    break
done

# Prompt for Bugsnag Project API Key (optional)
echo ""
read -p "🔑 Bugsnag Project API Key (optional, press Enter to skip): " BUGSNAG_PROJECT_API_KEY
if [ -z "$BUGSNAG_PROJECT_API_KEY" ]; then
    echo "ℹ️  No project API key provided. All projects will be accessible."
fi

# Test Grafana connectivity
echo ""
echo "🔍 Testing Grafana connection..."

API_URL="${GRAFANA_URL%/}/api/org"

if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -s -o /tmp/grafana_response.json -w "%{http_code}" \
        -H "Authorization: Bearer $GRAFANA_SERVICE_ACCOUNT_TOKEN" \
        -H "Content-Type: application/json" \
        "$API_URL" 2>/dev/null || echo "000")

    if [ "$HTTP_CODE" -eq 200 ]; then
        ORG_NAME=$(grep -o '"name":"[^"]*"' /tmp/grafana_response.json 2>/dev/null | cut -d'"' -f4 || echo "Unknown")
        echo "✅ Successfully connected to Grafana organization: $ORG_NAME"
        rm -f /tmp/grafana_response.json
    else
        echo "❌ Connection test failed (HTTP $HTTP_CODE)"
        rm -f /tmp/grafana_response.json
        read -p "⚠️  Continue anyway? (y/N): " CONTINUE
        if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
            echo "Setup cancelled."
            exit 1
        fi
    fi
else
    echo "⚠️  curl not found, skipping connection test"
fi

# Test Bugsnag connectivity
echo ""
echo "🔍 Testing Bugsnag connection..."

BUGSNAG_API_URL="https://api.bugsnag.com/user/organizations"

if command -v curl &> /dev/null; then
    HTTP_CODE=$(curl -s -o /tmp/bugsnag_response.json -w "%{http_code}" \
        -H "Authorization: token $BUGSNAG_AUTH_TOKEN" \
        -H "X-Version: 2" \
        "$BUGSNAG_API_URL" 2>/dev/null || echo "000")

    if [ "$HTTP_CODE" -eq 200 ]; then
        # Try to extract first organization name from JSON array
        ORG_NAME=$(grep -o '"name":"[^"]*"' /tmp/bugsnag_response.json 2>/dev/null | head -1 | cut -d'"' -f4 || echo "Unknown")
        echo "✅ Successfully connected to Bugsnag (Organization: $ORG_NAME)"
        rm -f /tmp/bugsnag_response.json
    else
        echo "❌ Connection test failed (HTTP $HTTP_CODE)"
        rm -f /tmp/bugsnag_response.json
        read -p "⚠️  Continue anyway? (y/N): " CONTINUE
        if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
            echo "Setup cancelled."
            exit 1
        fi
    fi
else
    echo "⚠️  curl not found, skipping connection test"
fi

# Create .env file
cat > "$ENV_FILE" << EOF
# Grafana Configuration
GRAFANA_URL=$GRAFANA_URL
GRAFANA_SERVICE_ACCOUNT_TOKEN=$GRAFANA_SERVICE_ACCOUNT_TOKEN

# Bugsnag Configuration (SmartBear MCP)
BUGSNAG_AUTH_TOKEN=$BUGSNAG_AUTH_TOKEN
BUGSNAG_PROJECT_API_KEY=$BUGSNAG_PROJECT_API_KEY

# Generated by setup script on $(date -Iseconds 2>/dev/null || date)
EOF

echo ""
echo "✅ Environment file created successfully: $ENV_FILE"
echo "🎉 Setup complete! The devcontainer will now start."
echo ""
